"use client";

import { useState, useEffect } from 'react';
import Image, { ImageProps } from 'next/image';
import { cn } from '@/lib/utils';
// @ts-ignore - File is generated by script
import imageMapData from '@/generated/images-map.json';

interface OptimizedImageProps extends Omit<ImageProps, 'src'> {
  src: string;
  className?: string;
  alt: string;
}

const OptimizedImage = ({ src, alt, className, priority, ...props }: OptimizedImageProps) => {
  const [isLoaded, setIsLoaded] = useState(false);

  // Normalize path to match keys in JSON (ensure leading slash)
  const normalizedSrc = src.startsWith('/') ? src : `/${src}`;
  const optimizedData = (imageMapData as any)[normalizedSrc];

  // 1. Case: Image data exists in our map (Optimized)
  if (optimizedData) {
    const { avif, webp, placeholder, original } = optimizedData;

    // Generate srcSet strings
    const avifSrcSet = avif.map((v: any) => `${v.src} ${v.width}w`).join(', ');
    const webpSrcSet = webp.map((v: any) => `${v.src} ${v.width}w`).join(', ');

    return (
      <div className={cn("relative overflow-hidden", className)}>
        {/* Placeholder (Blur Layer) */}
        <div
          aria-hidden="true"
          className={cn(
            "absolute inset-0 bg-cover bg-center transition-opacity duration-500 will-change-opacity",
            isLoaded ? "opacity-0" : "opacity-100"
          )}
          style={{ backgroundImage: `url(${placeholder})`, filter: 'blur(20px)', transform: "scale(1.1)" }}
        />

        <picture>
          <source srcSet={avifSrcSet} type="image/avif" sizes="(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 33vw" />
          <source srcSet={webpSrcSet} type="image/webp" sizes="(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 33vw" />
          <img
            src={original}
            alt={alt}
            decoding={priority ? "sync" : "async"}
            loading={priority ? "eager" : "lazy"}
            className={cn(
              "w-full h-auto object-cover transition-opacity duration-500",
              isLoaded ? "opacity-100" : "opacity-0"
            )}
            onLoad={() => setIsLoaded(true)}
            {...props}
          />
        </picture>
      </div>
    );
  }

  // 2. Fallback: Use standard Next.js Image for unoptimized assets
  return (
    <div className={cn("relative overflow-hidden", className)}>
      <Image
        src={src}
        alt={alt}
        className={cn("transition-opacity duration-500", isLoaded ? "opacity-100" : "opacity-0")}
        onLoad={(e) => {
          const target = e.target as HTMLImageElement;
          if (target.src.indexOf('data:') !== 0) setIsLoaded(true);
        }}
        {...props}
      />
    </div>
  );
};

export default OptimizedImage;
